{ bux/RUB bux.currencies/RUB
  bux/BND bux.currencies/BND
  bux/NZD bux.currencies/NZD
  bux/CDF bux.currencies/CDF
  bux/PLN bux.currencies/PLN
  bux/WST bux.currencies/WST
  bux/BIF bux.currencies/BIF
  bux/BDT bux.currencies/BDT
  bux/ZMK bux.currencies/ZMK
  bux/VND bux.currencies/VND
  bux/RWF bux.currencies/RWF
  bux/ZAR bux.currencies/ZAR
  bux/TWD bux.currencies/TWD
  bux/HKD bux.currencies/HKD
  bux/LAK bux.currencies/LAK
  bux/VEF bux.currencies/VEF
  bux/TZS bux.currencies/TZS
  bux/AED bux.currencies/AED
  bux/SOS bux.currencies/SOS
  bux/VUV bux.currencies/VUV
  bux/KGS bux.currencies/KGS
  bux/TND bux.currencies/TND
  bux/NIO bux.currencies/NIO
  bux/RSD bux.currencies/RSD
  bux/TMM bux.currencies/TMM
  bux/EUR bux.currencies/EUR
  bux/PAB bux.currencies/PAB
  bux/BYR bux.currencies/BYR
  bux/UAH bux.currencies/UAH
  bux/CAD bux.currencies/CAD
  bux/MYR bux.currencies/MYR
  bux/NAD bux.currencies/NAD
  bux/BTN bux.currencies/BTN
  bux/SGD bux.currencies/SGD
  bux/ZWD bux.currencies/ZWD
  bux/DKK bux.currencies/DKK
  bux/SKK bux.currencies/SKK
  bux/BHD bux.currencies/BHD
  bux/ETB bux.currencies/ETB
  bux/HUF bux.currencies/HUF
  bux/KMF bux.currencies/KMF
  bux/BMD bux.currencies/BMD
  bux/KWD bux.currencies/KWD
  bux/LSL bux.currencies/LSL
  bux/DOP bux.currencies/DOP
  bux/PHP bux.currencies/PHP
  bux/GNF bux.currencies/GNF
  bux/SDG bux.currencies/SDG
  bux/BZD bux.currencies/BZD
  bux/KYD bux.currencies/KYD
  bux/MZN bux.currencies/MZN
  bux/ERN bux.currencies/ERN
  bux/SVC bux.currencies/SVC
  bux/IDR bux.currencies/IDR
  bux/EGP bux.currencies/EGP
  bux/BAM bux.currencies/BAM
  bux/DZD bux.currencies/DZD
  bux/MOP bux.currencies/MOP
  bux/ARS bux.currencies/ARS
  bux/QAR bux.currencies/QAR
  bux/BOB bux.currencies/BOB
  bux/KHR bux.currencies/KHR
  bux/MDL bux.currencies/MDL
  bux/IQD bux.currencies/IQD
  bux/CUC bux.currencies/CUC
  bux/YER bux.currencies/YER
  bux/HTG bux.currencies/HTG
  bux/AUD bux.currencies/AUD
  bux/ANG bux.currencies/ANG
  bux/ILS bux.currencies/ILS
  bux/TJS bux.currencies/TJS
  bux/SAR bux.currencies/SAR
  bux/TTD bux.currencies/TTD
  bux/SEK bux.currencies/SEK
  bux/CUP bux.currencies/CUP
  bux/BSD bux.currencies/BSD
  bux/LTL bux.currencies/LTL
  bux/SLL bux.currencies/SLL
  bux/XCD bux.currencies/XCD
  bux/GMD bux.currencies/GMD
  bux/KES bux.currencies/KES
  bux/GYD bux.currencies/GYD
  bux/SRD bux.currencies/SRD
  bux/KZT bux.currencies/KZT
  bux/JOD bux.currencies/JOD
  bux/SZL bux.currencies/SZL
  bux/GHS bux.currencies/GHS
  bux/KPW bux.currencies/KPW
  bux/JMD bux.currencies/JMD
  bux/MWK bux.currencies/MWK
  bux/ISK bux.currencies/ISK
  bux/INR bux.currencies/INR
  bux/MRO bux.currencies/MRO
  bux/PKR bux.currencies/PKR
  bux/PGK bux.currencies/PGK
  bux/IRR bux.currencies/IRR
  bux/AFN bux.currencies/AFN
  bux/CRC bux.currencies/CRC
  bux/OMR bux.currencies/OMR
  bux/UZS bux.currencies/UZS
  bux/CNY bux.currencies/CNY
  bux/THB bux.currencies/THB
  bux/XPF bux.currencies/XPF
  bux/CZK bux.currencies/CZK
  bux/MVR bux.currencies/MVR
  bux/AZN bux.currencies/AZN
  bux/NGN bux.currencies/NGN
  bux/TOP bux.currencies/TOP
  bux/BRL bux.currencies/BRL
  bux/MKD bux.currencies/MKD
  bux/BWP bux.currencies/BWP
  bux/SHP bux.currencies/SHP
  bux/USD bux.currencies/USD
  bux/TRY bux.currencies/TRY
  bux/RON bux.currencies/RON
  bux/UYU bux.currencies/UYU
  bux/MAD bux.currencies/MAD
  bux/MGA bux.currencies/MGA
  bux/LBP bux.currencies/LBP
  bux/XAF bux.currencies/XAF
  bux/COP bux.currencies/COP
  bux/LRD bux.currencies/LRD
  bux/LKR bux.currencies/LKR
  bux/AMD bux.currencies/AMD
  bux/CVE bux.currencies/CVE
  bux/CHF bux.currencies/CHF
  bux/HRK bux.currencies/HRK
  bux/FKP bux.currencies/FKP
  bux/MMK bux.currencies/MMK
  bux/ALL bux.currencies/ALL
  bux/NOK bux.currencies/NOK
  bux/LYD bux.currencies/LYD
  bux/FJD bux.currencies/FJD
  bux/SYP bux.currencies/SYP
  bux/MUR bux.currencies/MUR
  bux/DJF bux.currencies/DJF
  bux/GIP bux.currencies/GIP
  bux/BGN bux.currencies/BGN
  bux/STD bux.currencies/STD
  bux/MXN bux.currencies/MXN
  bux/GEL bux.currencies/GEL
  bux/LVL bux.currencies/LVL
  bux/GBP bux.currencies/GBP
  bux/SCR bux.currencies/SCR
  bux/XOF bux.currencies/XOF
  bux/SBD bux.currencies/SBD
  bux/UGX bux.currencies/UGX
  bux/HNL bux.currencies/HNL
  bux/AWG bux.currencies/AWG
  bux/NPR bux.currencies/NPR
  bux/CLP bux.currencies/CLP
  bux/KRW bux.currencies/KRW
  bux/JPY bux.currencies/JPY
  bux/MNT bux.currencies/MNT
  bux/AOA bux.currencies/AOA
  bux/PEN bux.currencies/PEN
  bux/PYG bux.currencies/PYG
  bux/BBD bux.currencies/BBD
  bux/GTQ bux.currencies/GTQ}